### ISSUE TITLE
candidate: infra.middleware_ocpv (formerly infra.ocpv_lab)

### ISSUE THREAD

**Issue by alisonlhart** [ansible/validated-content-discussion#16]
#### Candidate Name
infra.middleware_ocpv

#### Link to Github Repo
https://github.com/redhat-cop/middleware_ocpv

#### Review Due By
Jan 24

#### Business Checks:

**Content Viability** 
- [x] must support a “business-viable” use case
- [x] isn’t just a demo
- [x] is production-ready, as in able to run in Ansible Controller “as-is”
- [x] provides a solution an end-to-end automation use case and brings value to our customers

**Content Duplication**
- [x] use case addressed by the content isn’t covered by another validated content collection already - to the best of our knowledge

#### Technical Checks:

**Content Conformity**
- [x] is packaged as a content collection - see the [Collection Requirements Checklist](https://github.com/ansible-collections/overview/blob/main/collection_checklist.md)
- [x] is YAML only (Exception: if plugin(s) included are necessary for this specific use-case and are not generic enough for a certified collection)
- [x] if there is a plugin(s), it is not a duplicate of something from a certified or supported collection - to the best of our knowledge
- [x] supported plugin/module used in a validated role is noted as a dependency

**Content Compliance** 
- [x] no known policy or legal reason for why the content shouldn’t be published
- [x] README contains information about the purpose of the collection and how to install it
- [x] README contains a link to the collection license file
- [x] README contains general usage and requirements information such as required versions of ansible-core and Python, and other required libraries or SDKs
- [x] Repo is self-certified with the [OpenSSF Best Practices](https://bestpractices.coreinfrastructure.org/en) and has the OpenSSF Best Practices Badge 
- [x] Has 2 or more active maintainers listed in a CODEOWNERS file. 
- [x] Has an approved OSI license 
- [x] Content falls logically into one of these domains - infra, security, network, cloud, edge
- [x] (If internal content) Content has been or is being migrated into the redhat-cop Github org

**Content Testing/Validation**
- [x] runs `ansible-lint` “Production” profile in an active Github workflow on the repository
- [x] passes the `ansible-lint` “Production” profile
- [x] ansible-lint.yml file (if present) only contains justified ignores - with a comment explaining the need for each ignore

**Comment by alisonlhart** [comment]
Candidate namespace needs to be one of the generic namespaces - infra, security, network, cloud, edge. 
My suggestion would be `infra` or `cloud`.

**Comment by alisonlhart** [comment]
@arnav3000 For review at your availability. :)

**Comment by arnav3000** [comment]
ansible-lint passes the test however it only runs in offline mode and the file .ansible-lint excludes running on playbooks/roles.

**Comment by alisonlhart** [comment]
Requirements.yml does not include ansible.posix, which is listed in the galaxy.yml file as a dependency.

**Comment by RanabirChakraborty** [comment]
Hello @arnav3000 As the collection requires an OpenShift token, we can't run ansible-lint in online mode. That's why we opted for offline mode.

**Comment by arnav3000** [comment]
Hi @RanabirChakraborty , Can you run the ansible lint tests again without exclusions. Also if there are specific files that needs to be excluded in ansible lint, please provide the justification.

**Comment by RanabirChakraborty** [comment]
@arnav3000 I have modified the `ansible-lint` it should be fine now. 
@alisonlhart I have included `ansible.posix` in Requirements.yml
Please review the collection once the PR gets merged.

**Comment by arnav3000** [comment]
Hi @RanabirChakraborty,
Can you also add the business justification or a use case to the repository ?

**Comment by RanabirChakraborty** [comment]
Hello @arnav3000 Do you want me to add the use case or business justification inside the README file or inside some other file?

**Comment by RanabirChakraborty** [comment]
@arnav3000 @alisonlhart added the use case part inside the repository. Thanks!

**Comment by alisonlhart** [comment]
Remaining items:
- OpenSSF Badge
- Use one of the validated content allocated namespaces - `infra`, `network`, `cloud`, `security`, `edge`. 
- Migrate content into the redhat-cop Github Org. Open a `repository management` issue [here](https://github.com/redhat-cop/org/issues/new/choose). Reach out to `@Andrew Block` in RH slack with any migration questions. 
@RanabirChakraborty

**Comment by RanabirChakraborty** [comment]
Hello @alisonlhart @arnav3000 , We have already fulfilled all the requirements and you can now check the repo - https://github.com/redhat-cop/ocpv_lab. Can you please review it now. Thanks!

**Comment by alisonlhart** [comment]
All requirements are now passing! :confetti_ball: I will bring this to the ACoP call today.

**Comment by alisonlhart** [comment]
I brought this to the ACoP call today asking for additional review. The official sign-off date is Jan 24 for any additional review comments or suggestions from ACoP.

**Comment by chynasan** [comment]
When presenting this to the ACoP for review, there was concern raised that this is only for demo use, which does not meet the standards for the checklist.

**Comment by chynasan** [comment]
The collection maintainers have updated the name and documentation for this collection and were hoping to have this re-reviewed. I am going to follow-up with the Community of Practice to request additional review.

**Comment by chynasan** [comment]
Presented to the ACoP as a request for re-review Feb 21st.

**Comment by alisonlhart** [comment]
No additional input from the ACoP on this. Candidate has been approved and can be uploaded to Automation Hub at your convenience @RanabirChakraborty. If you do not currently have access to the `infra` namespace, please reach out to me on slack and we'll get that set up.
