### ISSUE TITLE
candidate: infra.lvm_snapshots

### ISSUE THREAD

**Issue by swapdisk** [ansible/validated-content-discussion#20]
#### Candidate Name
`infra.lvm_snapshots`

#### Link to Github Repo
[link](https://github.com/swapdisk/infra.lvm_snapshots)

#### Review Due By
Jan 10

#### Business Checks:

**Content Viability** 
- [x] must support a “business-viable” use case
- [x] isn’t just a demo
- [x] is production-ready, as in able to run in Ansible Controller “as-is”
- [x] provides a solution an end-to-end automation use case and brings value to our customers

**Content Duplication**
- [x] use case addressed by the content isn’t covered by another validated content collection already - to the best of our knowledge

#### Technical Checks:

**Content Conformity**
- [x] is packaged as a content collection - see the [Collection Requirements Checklist](https://github.com/ansible-collections/overview/blob/main/collection_checklist.md)
- [x] is YAML only (Exception: if plugin(s) included are necessary for this specific use-case and are not generic enough for a certified collection)
- [x] if there is a plugin(s), it is not a duplicate of something from a certified or supported collection - to the best of our knowledge
- [x] supported plugin/module used in a validated role is noted as a dependency

**Content Compliance** 
- [x] no known policy or legal reason for why the content shouldn’t be published
- [x] README contains information about the purpose of the collection and how to install it
- [x] README contains a link to the collection license file
- [x] README contains general usage and requirements information such as required versions of ansible-core and Python, and other required libraries or SDKs
- [x] Repo is self-certified with the [OpenSSF Best Practices](https://bestpractices.coreinfrastructure.org/en) and has the OpenSSF Best Practices Badge 
- [x] Has 2 or more active maintainers listed in a CODEOWNERS file. 
- [x] Has an approved OSI license 
- [x] Content falls logically into one of these domains - infra, security, network, cloud, edge
- [x] (If internal content) Content has been or is being migrated into the redhat-cop Github org

**Content Testing/Validation**
- [x] runs `ansible-lint` “Production” profile in an active Github workflow on the repository
- [x] passes the `ansible-lint` “Production” profile
- [x] ansible-lint.yml file (if present) only contains justified ignores - with a comment explaining the need for each ignore

**Comment by alisonlhart** [comment]
@sean-m-sullivan @djdanielsson If you have time to look over this candidate, that would be great!

**Comment by ericzolf** [comment]
After a quick check:
1. not all points have been ticked, what is exactly the status?
2. I find the idea to name the collection like one of the roles questionable, perhaps a better name is possible, covering all aspects of the collection?
3. the variables haven't been named according to standard, with proper prefix
4. the tasks name are not prefixed with the name of the task file
5. the `lvm_snapshots` role is IMHO too complex and should be split into one role for each action to keep it/them nice and tidy (and avoid too many skipped tasks)

**Comment by alisonlhart** [comment]
A Requirements section with the required version of ansible should be added to the README, and the dependency of community.general should also be noted in that README section. 
The `meta/runtime.yml` "requires_ansible" key should be bumped up to 2.14.0, since all previous versions of Ansible are EoL.

**Comment by swapdisk** [comment]
@ericzolf and @alisonlhart, we've made changes to the candidate collection to address your kind feedback. Please take a fresh look at your convenience.

**Comment by alisonlhart** [comment]
@swapdisk I believe all points have been addressed and items are checked, but I'll wait for sign-off from @ericzolf and also run the changes by the ACoP before final approval.

**Comment by alisonlhart** [comment]
Final sign-off for this will be Jan 10.

**Comment by alisonlhart** [comment]
Candidate has been approved! At this time, please reach out to `@ansible-pe` in the `#ansible-partners` slack channel for assistance on next steps, or email ansiblepartners@redhat.com so we can set up your access to the infra namespace.
