### ISSUE TITLE
candidate: cloud.gcp_ops

### ISSUE THREAD

**Issue by alinabuzachis** [ansible/validated-content-discussion#21]
#### Candidate Name

cloud.gcp_ops

#### Link to Github Repo

https://github.com/redhat-cop/cloud.gcp_ops

#### Review Due By
Jan 24

#### Business Checks:

**Content Viability** 
- [x] must support a “business-viable” use case
- [x] isn’t just a demo
- [x] is production-ready, as in able to run in Ansible Controller “as-is”
- [x] provides a solution an end-to-end automation use case and brings value to our customers

**Content Duplication**
- [x] use case addressed by the content isn’t covered by another validated content collection already - to the best of our knowledge

#### Technical Checks:

**Content Conformity**
- [x] is packaged as a content collection - see the [Collection Requirements Checklist](https://github.com/ansible-collections/overview/blob/main/collection_checklist.md)
- [x] is YAML only (Exception: if plugin(s) included are necessary for this specific use-case and are not generic enough for a certified collection)
- [x] if there is a plugin(s), it is not a duplicate of something from a certified or supported collection - to the best of our knowledge
- [x] supported plugin/module used in a validated role is noted as a dependency

**Content Compliance** 
- [x] no known policy or legal reason for why the content shouldn’t be published
- [x] README contains information about the purpose of the collection and how to install it
- [x] README contains a link to the collection license file
- [x] README contains general usage and requirements information such as required versions of ansible-core and Python, and other required libraries or SDKs
- [ ] Repo is self-certified with the [OpenSSF Best Practices](https://bestpractices.coreinfrastructure.org/en) and has the OpenSSF Best Practices Badge 
- [x] Has 2 or more active maintainers listed in a CODEOWNERS file. 
- [x] Has an approved OSI license 
- [x] Content falls logically into one of these domains - infra, security, network, cloud, edge
- [x] (If internal content) Content has been or is being migrated into the redhat-cop Github org

**Content Testing/Validation**
- [x] runs `ansible-lint` “Production” profile in an active Github workflow on the repository
- [x] passes the `ansible-lint` “Production” profile
- [x] ansible-lint.yml file (if present) only contains justified ignores - with a comment explaining the need for each ignore

**Comment by alisonlhart** [comment]
@arnav3000 Check this one out at your convenience!

**Comment by alisonlhart** [comment]
I will bring this in front of the ACoP for review, with final sign-off by the 24th.

**Comment by arnav3000** [comment]
@alinabuzachis - Can you please confirm if ansible-lint is running with "Production" profile. I do not see it in configured in GitHub actions.

**Comment by alinabuzachis** [comment]
> @alinabuzachis - Can you please confirm if ansible-lint is running with "Production" profile. I do not see it in configured in GitHub actions.

@alisonlhart it should because the profile seems configured here https://github.com/redhat-cop/cloud.gcp_ops/blob/main/.config/ansible-lint.yml

**Comment by arnav3000** [comment]
@alinabuzachis - I read this file but in the actions, I do not see anything which is running ansible-lint. Can you please point me to that stage ?

**Comment by alinabuzachis** [comment]
> @alinabuzachis - I read this file but in the actions, I do not see anything which is running ansible-lint. Can you please point me to that stage ?

@alisonlhart this is the log from a PR merged last month https://github.com/redhat-cop/cloud.gcp_ops/actions/runs/7210522394/job/19643866595#step:3:227

**Comment by alisonlhart** [comment]
@alinabuzachis Someone from the Automation CoP pointed out that the "Installation" section is the old pre-Automation Hub method of install from Github. Can you update this to the typical "ansible-galaxy install <x>" install command? 

So far, the only other missing item is the OpenSSF badge. There may be more feedback from the ACoP coming though, since the candidate will be discussing in the upcoming Jan 10 ACoP meeting.

**Comment by alinabuzachis** [comment]
@alisonlhart I updated the installation process. Let me know please if anything else is needed. Thank you.

**Comment by alinabuzachis** [comment]
> @alinabuzachis Thank you! I brought this to the ACoP call today asking for additional review. The official sign-off date is Jan 24 for any additional review comments or suggestions from ACoP.

@alisonlhart Awesome, thank you!

**Comment by chynasan** [comment]
@alinabuzachis I talked to the ACoP about this again today and there were no concerns raised about it so I think we should be good to move forward!

**Comment by alisonlhart** [comment]
We're going to do a security evaluation of the OpenSSF badge. With this in mind, we're approving this collection without that req in place. :fireworks:
