### ISSUE TITLE
candidate: infra.convert2rhel

### ISSUE THREAD

**Issue by r0x0d** [ansible/validated-content-discussion#27]
#### Candidate Name

infra.convert2rhel

#### Link to Github Repo

https://github.com/redhat-cop/infra.convert2rhel

#### Review Due By

03/25/2024

#### Business Checks:

**Content Viability** 
- [x] must support a “business-viable” use case
- [x] isn’t just a demo
- [x] is production-ready, as in able to run in Ansible Controller “as-is”
- [x] provides a solution an end-to-end automation use case and brings value to our customers

**Content Duplication**
- [x] use case addressed by the content isn’t covered by another validated content collection already - to the best of our knowledge

#### Technical Checks:

**Content Conformity**
- [x] is packaged as a content collection - see the [Collection Requirements Checklist](https://github.com/ansible-collections/overview/blob/main/collection_checklist.md)
- [x] is YAML only (Exception: if plugin(s) included are necessary for this specific use-case and are not generic enough for a certified collection)
- [x] if there is a plugin(s), it is not a duplicate of something from a certified or supported collection - to the best of our knowledge
- [x] supported plugin/module used in a validated role is noted as a dependency

**Content Compliance** 
- [x] no known policy or legal reason for why the content shouldn’t be published
- [x] README contains information about the purpose of the collection and how to install it
- [x] README contains a link to the collection license file
- [x] README contains general usage and requirements information such as required versions of ansible-core and Python, and other required libraries or SDKs
- [x] install / requirements.yml information all points to Automation Hub, not a Github repo
- [x] Repo is self-certified with the [OpenSSF Best Practices](https://bestpractices.coreinfrastructure.org/en) and has the OpenSSF Best Practices Badge 
- [x] Has 2 or more active maintainers listed in a CODEOWNERS file. 
- [x] Has an approved OSI license 
- [x] Content falls logically into one of these domains - infra, security, network, cloud, edge
- [x] (If internal content) Content has been or is being migrated into the redhat-cop Github org

**Content Testing/Validation**
- [x] runs `ansible-lint` “Production” profile in an active Github workflow on the repository
- [x] passes the `ansible-lint` “Production” profile
- [x] ansible-lint.yml file (if present) only contains justified ignores - with a comment explaining the need for each ignore

**Comment by alisonlhart** [comment]
@djdanielsson @arnav3000 @ericzolf @sean-m-sullivan Can you take a look at this candidate?

**Comment by djdanielsson** [comment]
checklist isn't done, but skimming some of the code I think it is good.

**Comment by r0x0d** [comment]
Hi, it's been some time now... Should I check the boxes myself, or is this job for someone else to do?

**Comment by djdanielsson** [comment]
it is your job to check the boxes

**Comment by r0x0d** [comment]
Hi, @heatmiser, could you take a look for the `Content Viability` section, please? Thanks.

**Comment by heatmiser** [comment]
@r0x0d All items in Content Viability section are covered.

**Comment by r0x0d** [comment]
@alisonlhart, all items in check list are done.

**Comment by alisonlhart** [comment]
@r0x0d A few items I saw during review:
- The galaxy.yml file includes a dep on fedora.linux_system_roles. This should be changed to the certified redhat.rhel_system_roles collection (downstream version of the same collection)
- No CODEOWNERS file included
- Is there a workflow running ansible-lint? [This workflow](https://github.com/redhat-cop/infra.convert2rhel/blob/main/.github/workflows/pre-commit.yml#L2) says it in the name, but I don't see where the linter is actually running in the workflow.

**Comment by alisonlhart** [comment]
@r0x0d Thank you for pointing me to the correct file! I figured I was just missing it somewhere. After the PR is merged, I believe that meets all checklist criteria. I'll add this to the sign-off list for this week's ACoP call on April 17.

**Comment by alisonlhart** [comment]
Approved by the ACoP! @r0x0d please reach out to me on slack `@allhart` to get your access to the infra namespace on Automation Hub.

**Comment by r0x0d** [comment]
> Approved by the ACoP! @r0x0d please reach out to me on slack `@allhart` to get your access to the infra namespace on Automation Hub set up.

Thanks, @alisonlhart!  

We just merged https://github.com/redhat-cop/infra.convert2rhel/pull/41 and will be generating a new release soon!
