### ISSUE TITLE
candidate: infra.eda_configuration

### ISSUE THREAD

**Issue by Tompage1994** [ansible/validated-content-discussion#31]
#### Candidate Name
infra.eda_configuration

#### Link to Github Repo
https://github.com/redhat-cop/eda_configuration

#### Review Due By
22 April 2024

#### Business Checks:

**Content Viability** 
- [X] must support a “business-viable” use case
- [X] isn’t just a demo
- [X] is production-ready, as in able to run in Ansible Controller “as-is”
- [X] provides a solution an end-to-end automation use case and brings value to our customers

**Content Duplication**
- [X] use case addressed by the content isn’t covered by another validated content collection already - to the best of our knowledge

#### Technical Checks:

**Content Conformity**
- [X] is packaged as a content collection - see the [Collection Requirements Checklist](https://github.com/ansible-collections/overview/blob/main/collection_checklist.md)
- [X] is YAML only (Exception: if plugin(s) included are necessary for this specific use-case and are not generic enough for a certified collection)
- [X] if there is a plugin(s), it is not a duplicate of something from a certified or supported collection - to the best of our knowledge
- [X] supported plugin/module used in a validated role is noted as a dependency

**Content Compliance** 
- [X] no known policy or legal reason for why the content shouldn’t be published
- [X] README contains information about the purpose of the collection and how to install it
- [X] README contains a link to the collection license file
- [X] README contains general usage and requirements information such as required versions of ansible-core and Python, and other required libraries or SDKs
- [X] install / requirements.yml information all points to Automation Hub, not a Github repo
- [x] Repo is self-certified with the [OpenSSF Best Practices](https://bestpractices.coreinfrastructure.org/en) and has the OpenSSF Best Practices Badge 
- [x] Has 2 or more active maintainers listed in a CODEOWNERS file. (YES, not in CODEOWNERS, owners are redhat-cop)
- [X] Has an approved OSI license 
- [X] Content falls logically into one of these domains - infra, security, network, cloud, edge
- [X] (If internal content) Content has been or is being migrated into the redhat-cop Github org

**Content Testing/Validation**
- [X] runs `ansible-lint` “Production” profile in an active Github workflow on the repository
- [X] passes the `ansible-lint` “Production” profile
- [X] ansible-lint.yml file (if present) only contains justified ignores - with a comment explaining the need for each ignore

**Comment by djdanielsson** [comment]
looks good to me

**Comment by alisonlhart** [comment]
Approved by the ACop!
