### ISSUE TITLE
candidate: edge.microshift

### ISSUE THREAD

**Issue by alisonlhart** [ansible/validated-content-discussion#9]
#### Candidate Name
edge.microshift

#### Link to Github Repo
https://github.com/ansible-collections/edge.microshift

#### Review Due By
**June 27** (Expedited review for 2.4 release)

#### Business Checks:

**Content Viability** 
- [x] must support a “business-viable” use case
- [x] isn’t just a demo
- [x] is production-ready, as in able to run in Ansible Controller “as-is”
- [x] provides a solution an end-to-end automation use case and brings value to our customers

**Content Duplication**
- [x] use case addressed by the content isn’t covered by another validated content collection already - to the best of our knowledge

#### Technical Checks:

**Content Conformity**
- [x] is packaged as a content collection - see the [Collection Requirements Checklist](https://github.com/ansible-collections/overview/blob/main/collection_checklist.md)
- [x] is YAML only (Exception: if plugin(s) included are necessary for this specific use-case and are not generic enough for a certified collection)
- [x] if there is a plugin(s), it is not a duplicate of something from a certified or supported collection - to the best of our knowledge
- [x] supported plugin/module used in a validated role is noted as a dependency

**Content Compliance** 
- [x] no known policy or legal reason for why the content shouldn’t be published
- [x] README contains information about the purpose of the collection and how to install it
- [x] README contains a link to the collection license file
- [x] README contains general usage and requirements information such as required versions of ansible-core and Python, and other required libraries or SDKs
- [x] Repo is self-certified with the [OpenSSF Best Practices](https://bestpractices.coreinfrastructure.org/en) and has the OpenSSF Best Practices Badge 
- [x] Has 2 or more active maintainers listed in a CODEOWNERS file. 
- [x] Has an approved OSI license 
- [x] Content falls logically into one of these domains - infra, security, network, cloud, edge
- [x] (If internal content) Content has been or is being migrated into the redhat-cop Github org

**Content Testing/Validation**
- [x] runs `ansible-lint` “Production” profile in an active Github workflow on the repository
- [x] passes the `ansible-lint` “Production” profile
- [x] ansible-lint.yml file (if present) only contains justified ignores - with a comment explaining the need for each ignore

**Comment by alisonlhart** [comment]
Initial review has resulting in the following remaining items:

- runs ansible-lint “Production” profile in an active Github workflow on the repository
- passes the ansible-lint “Production” profile
-  (If internal content) Content has been or is being migrated into the redhat-cop Github org
-  Has 2 or more active maintainers listed in a CODEOWNERS file.
-  supported plugin/module used in a validated role is noted as a dependency: the infra.osbuild validated content collection is a dependency and is not documented in the README as a dep.

**Comment by alisonlhart** [comment]
Candidate also has a dependency on community.general which is not in the galaxy.yml file or the collection README. 

Note: This candidate will be moving to certified later this year, when the community.general dep will have to be removed. As validated content, though, this is fine for now.

**Comment by alisonlhart** [comment]
Candidate also needs to fix the "How to Use" section in the README, which currently says "FIXME".

**Comment by djdanielsson** [comment]
quick review looked pretty good, I would remove docs/docsite/links.yml if that isn't planned on being used or update to correct info

**Comment by ericzolf** [comment]
The readme states "NOTE: THIS COLLECTION IS UNDER ACTIVE DEVELOPMENT AND NOT READY FOR GENERAL USE" - I would though assume that a validated collection is ready for general use.

**Comment by omaciel** [comment]
https://github.com/ansible-collections/edge.microshift/pull/50 fyi to remove the `NOTE: THIS COLLECTION IS UNDER ACTIVE DEVELOPMENT AND NOT READY FOR GENERAL USE` notice.

**Comment by alisonlhart** [comment]
All items have been resolved. 

Content has been migrated into the redhat-cop Github org.

**Comment by alisonlhart** [comment]
Candidate has been added.
